CREATE SEQUENCE tarefas_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE tarefas (
    id BIGINT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    concluida BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
